name: corehive_store
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  animations: ^2.0.11
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  responsive_framework: ^1.5.1
  icons_plus: ^5.0.0
  get_storage: ^2.1.1
  intl: ^0.20.2
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  connectivity_plus: ^7.0.0
  logger: ^2.6.1
  flutter_animate: ^4.5.2
  url_launcher: ^6.3.2
  flutter_svg: ^2.2.1
  vibration: ^3.1.3
  oktoast: ^3.4.0
  firebase_messaging: ^16.0.1
  flutter_local_notifications: ^19.4.2
  flutter_easyloading: ^3.0.5
  smooth_page_indicator: ^1.2.1
  flutter_launcher_icons: ^0.14.4
  font_awesome_flutter: ^10.9.1
  rename: ^3.1.0
  path_provider: ^2.1.5
  persistent_bottom_nav_bar: ^6.2.1





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/launcher/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
